version: '3.8'

services:
  flight_management_service:
    build:
      context: ./flight_management_service
    ports:
      - "83:80"

  booking_service:
    build:
      context: ./booking_service
    ports:
      - "80:80"
    depends_on:
      - flight_management_service
