version: '3.8'

services:
  booking_service:
    build: ./booking_service
    ports:
      - "80:80"
    depends_on:
      - flight_management_service
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - AWS_DEFAULT_REGION=us-east-2

  flight_management_service:
    build: ./flight_management_service
    ports:
      - "83:80"
    environment:
      - DATABASE_URL=sqlite:///./test.db

  notification_service:
    build: ./notification_service
    ports:
      - "84:80"  # Expose port 80 in the container to port 84 on the host
    depends_on:
      - booking_service
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - QUEUE_URL=https://sqs.us-east-2.amazonaws.com/<AWS_ACCOUNT_ID>/MyQueue.fifo

  payment_service:
    build: ./payment_service
    ports:
      - "85:80"
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - DYNAMODB_TABLE=Payments
