name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: List directory contents
        run: ls -R
        working-directory: .

      # Booking Service
      - name: Install dependencies for Booking Service
        run: |
          cd booking_service/app
          ls -R
          pip install -r requirements.txt

      - name: Run tests for Booking Service
        run: |
          cd booking_service/app
          # Add your test command here

      # Flight Management Service
      - name: Install dependencies for Flight Management Service
        run: |
          cd flight_management_service/app
          ls -R
          pip install -r requirements.txt

      - name: Run tests for Flight Management Service
        run: |
          cd flight_management_service/app
          # Add your test command here

      # Notification Service
      - name: Install dependencies for Notification Service
        run: |
          cd notification_service/app
          ls -R
          pip install -r requirements.txt

      - name: Run tests for Notification Service
        run: |
          cd notification_service/app
          # Add your test command here

      # Payment Service
      - name: Install dependencies for Payment Service
        run: |
          cd payment_service/app
          ls -R
          pip install -r requirements.txt

      - name: Run tests for Payment Service
        run: |
          cd payment_service/app
          # Add your test command here

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker images
        run: |
          cd booking_service/app
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/booking_service:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/booking_service:latest
          cd ../../..

          cd flight_management_service/app
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flight_management_service:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flight_management_service:latest
          cd ../../..

          cd notification_service/app
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/notification_service:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/notification_service:latest
          cd ../../..

          cd payment_service/app
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/payment_service:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/payment_service:latest
          cd ../../..
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update ECS service with new task definition
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --force-new-deployment
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
